

# This file was *autogenerated* from the file ellipticCurvePoints.sage
from sage.all_cmdline import *   # import sage library

_sage_const_97 = Integer(97); _sage_const_41 = Integer(41); _sage_const_12 = Integer(12)# Elliptic curve and number of point on the curve

E= EllipticCurve(GF(_sage_const_97 ),[_sage_const_41 ,_sage_const_12 ])
print(E)
print("Number of points in the curve:",E.order())
print("Points in the elliptic curve:",E.points())

